server:
  port: 8000
#密码加密传输，前端公钥加密，后端私钥解密 rsa.private_key
rsa:
  public_key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALpDvk+LhR4dGvmmU5f1LU6KPRpi29LFm5E0cYhWSpHooYtZ5fxiBL9eO5cG3so5wh1cS9R+cWy6zX/JbKaPoekCAwEAAQ==
  private_key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAukO+T4uFHh0a+aZTl/UtToo9GmLb0sWbkTRxiFZKkeihi1nl/GIEv147lwbeyjnCHVxL1H5xbLrNf8lspo+h6QIDAQABAkA3APQ9Fy1LNDsYB9bdo8gqTkY2+YSCnFoRKhRwt1Kz/SZBOg9Mswrqq1X92y7DemkhiOPb4CF+ncAoZh8ICw/lAiEA5Rt99hqkHNI9m9CWhUZeEwyjnJV5iNZVqM+mXx2Om+sCIQDQINuZcMVU98XHe5svzHbCjP9bLC7Ig1tbjjQf2oooewIhAJXpllNp/UbKnvuM0mEkuTvXwlscR6ktLmHGdgO48G6/AiBvDJkfTeR8aZfF0FYFMvtK4yB87R4pLq1YNI/rTxfYcQIgBx6hbiPqBtBocdzQoFjNrNsLEJUv2qiV4T2H9nPEoSM=

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/eladmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  redis:
    # redis库
    database: 0
    # redis 服务器地址
    host: localhost
    # redis 端口号
    port: 6379
    # redis 密码
    password:
    # 连接超时时间（毫秒）
    timeout: 1000
    lettuce:
      pool:
        # 连接池最大链接数（负数表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        # 连接池最大空闲连接数
        max-idle: 8
        # 连接池最小空闲连接数
        min-idle: 0

